# Generated by Django 5.0.4 on 2024-09-15 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autosalon', '0011_partner_alter_order_date_sold_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_sold',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 15, 23, 15, 0, 726439)),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, default='partners/default_photo.png', upload_to='partners/'),
        ),
    ]
