# Generated by Django 5.0.4 on 2024-09-15 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autosalon', '0012_alter_order_date_sold_alter_partner_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_sold',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 1, 20, 7, 338356)),
        ),
    ]
