# Generated by Django 5.0.4 on 2024-09-16 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autosalon', '0019_cart_applied_discount_cart_promo_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcompany',
            name='certificate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_sold',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 15, 37, 41, 455700)),
        ),
    ]
