# Generated by Django 5.0.4 on 2024-09-16 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autosalon', '0020_aboutcompany_certificate_aboutcompany_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcompany',
            name='requisites',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_sold',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 15, 55, 23, 182977)),
        ),
    ]
