# Generated by Django 5.0.4 on 2024-09-16 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autosalon', '0021_aboutcompany_requisites_alter_order_date_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcompany',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='company_videos/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_sold',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 17, 16, 17, 759637)),
        ),
    ]
