# Generated by Django 5.0.4 on 2024-09-16 20:27

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autosalon', '0023_alter_employee_start_date_alter_order_date_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='note',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_sold',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 23, 27, 36, 543236)),
        ),
    ]
