# Generated by Django 5.0.4 on 2024-09-15 23:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autosalon', '0016_alter_order_date_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutcompany',
            name='banner',
        ),
        migrations.AlterField(
            model_name='aboutcompany',
            name='logo',
            field=models.ImageField(default='default_logo.png', upload_to='about_company/logos/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_sold',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 2, 43, 24, 819065)),
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_company/banners/')),
                ('url', models.URLField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='Autosalon.aboutcompany')),
            ],
        ),
    ]
