# Generated by Django 5.0.4 on 2024-09-16 02:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autosalon', '0018_alter_order_date_sold_cart_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='applied_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='cart',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Autosalon.promo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_sold',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 5, 33, 59, 712997)),
        ),
    ]
