# Generated by Django 5.0.4 on 2024-09-16 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autosalon', '0022_aboutcompany_video_file_alter_order_date_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_sold',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 18, 59, 24, 61920)),
        ),
    ]
