# Generated by Django 5.0.4 on 2024-09-16 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autosalon', '0024_alter_feedback_note_alter_order_date_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_sold',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 23, 49, 48, 513869)),
        ),
    ]
